# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  #csrf_protection: true

  # Note that the session will be started ONLY if you read or write from it.
  session: true

  #esi: true
  #fragments: true
  assets:
    json_manifest_path: "%kernel.project_dir%/public/build/manifest.json"
  http_method_override: true

when@test:
  framework:
    test: true
    profiler: { only_exceptions: false }
    session:
      storage_factory_id: session.storage.factory.mock_file
